### ISSUE TITLE
Popup notification not working

### ISSUE THREAD

**Issue by avongluck-r1soft** [sadiqmmm/clipboard-rails#1]
Really nice gem! Just what I was looking for!.

Popup notifications don't seem to be working in my Rails 4 app.

application.js:

```
//= require jquery
//= require jquery.turbolinks
//= require jquery_ujs
//= require clipboard
//= require turbolinks
//= require_tree .

$(document).ready(function(){
    var clip = new Clipboard('.clip');
});
```

view:

```
<button class="btn btn-default btn-xs clip" data-clipboard-text='<%= thing.id %>' style='width: 50px;'><%=thing.id.first(4) %>...</button>
```

**Comment by avongluck-r1soft** [comment]
Copy and pasting the example view code doesn't result in popup notifications as well.

The functionality works however in supported browsers.

**Comment by sadiqmmm** [comment]
Thanks for reporting.

This gem is only a wrapper of clipboard.js

But the demo website of the clipboard.js is using the other style library and custom javascript to have the popup like onclick "Copied" animation.  http://zenorocha.github.io/clipboard.js/

They are using http://primercss.io/tooltips/ css framework and some custom javascript to make that animation work.

**Comment by sadiqmmm** [comment]
I am planing to have that type of functionality out of the box in the gem. But it will take some time.

**Comment by sadiqmmm** [comment]
Add Tooltips + Highlight animation: https://github.com/sadiqmmm/clipboard-rails#add-tooltips--highlight-animation.

Added documentation on Readme.
