### ISSUE TITLE
Documentation Error trigger: 'click'

### ISSUE THREAD

**Issue by Ekkstein** [sadiqmmm/clipboard-rails#8]
Just a minor issue...but it took me an hour to figure out, what lead to this behaviour.

In your example, you set the tooltip with the option: trigger: 'click'.
The rest of the example implements a solution, that requires: trigger: 'manual'

The problem is, if you click the same element repeatedly, the timeout will interfere with the hide tooltip on click bootstrap functionality leading to the tooltip just flashing up and immediately hiding again. Thus breaking the hide after timeout presented in the documentation.

**Comment by sadiqmmm** [comment]
Hi,
Thank you for reporting.
Can you provide a pull request with the solution?
